server:
  port: 7000



eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@172.17.73.236:9000/eureka/
    register-with-eureka: false
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 7  #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-renewal-interval-in-seconds: 5     #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30

spring:
  application:
    name: springcloud-zuul


zuul:
  routes:
    combat:
      path: /combat/**
      strip-prefix: true
      serviceId: SPRINGCLOUD-CONSUMER
  host:
    max-per-route-connections: 500
    max-total-connections: 6000
    connect-timeout-millis: 70000
    socket-timeout-millis: 60000
  ribbon-isolation-strategy: thread
  ## 将默认延迟加载改为立即加载，以防止第一次访问应用时超市的现象
  ribbon:
    eager-load:
      enabled: true



hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 300000




ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
  MaxConnectionsPerHost: 500
  MaxTotalConnections: 2000
