server:
  port: 9000

eureka:
  instance:
    hostname: localhost
    ## 心跳间隔，5秒， 默认90秒
    lease-renewal-interval-in-seconds: 5
    ## 没有心跳的淘汰时间，10秒 默认180秒
    lease-expiration-duration-in-seconds: 10
  server:
    ## 中小规模下，自我保护模式坑比好处多，所以关闭它
    enable-self-preservation: false
    ## 心跳阈值计算周期，如果开启自我保护模式，可以改一下这个配置
    ## renewal-threshold-update-interval-ms: 120000
    ## 主动失效检测间隔,配置成5秒、默认60000L（60秒）
    eviction-interval-timer-in-ms: 5000
    ## 客户端的有效负载缓存应该更新的时间间隔，默认为30 * 1000毫秒
    response-cache-update-interval-ms: 3000
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  # 注册中心访问地址


spring:
  security:
    user:
      name: admin
      password: admin
