server:
  port: 8071

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@172.17.73.236:9000/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 7  #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-renewal-interval-in-seconds: 5     #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30

spring:
  application:
    name: springcloud-consumer

ribbon:
  ReadTimeout: 100
  ConnectTimeout: 150