server:
  port: 9000
  
spring:
  application:
    name: zuul-gateway
  datasource:
    url: jdbc:mysql://47.94.211.209:8306/tusdao_audit?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: Tusdao@mysql2019*
    driver-class-name: com.mysql.jdbc.Driver
    
#eureka:
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@127.0.0.1:9000/eureka/
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 7  #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己），默认90
    lease-renewal-interval-in-seconds: 5     #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则），默认30

zuul:
  retryable: true