server:
  port: 8200

spring:
  application:
    name: springboot-mybatis-xml-mult

#数据库设置
  datasource:
    test1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.94.211.209:8306/mysql_test?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: Tusdao@mysql2019*

    test2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://47.94.211.209:8306/mysql_test1?characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false&useSSL=false
      username: root
      password: Tusdao@mysql2019*


    druid:
      initial-size: 5
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      max-active: 50
      min-idle: 5
      filters: wall,stat
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  check-config-location: true
